In [13]:
import pandas as pd

In [14]:
ELEC_DATA_PATH = '../Data/electric_df_28_days.csv'
WATER_DATA_PATH = '../Data/water_df_28_days.csv'

In [15]:
electric_df = pd.read_csv(ELEC_DATA_PATH)
water_df = pd.read_csv(WATER_DATA_PATH)

electric_df.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,18,19,20,21,22,23,24,25,26,27
0,0,1.23,1.45,1.73,1.62,1.31,1.48,1.74,1.71,1.30,...,1.77,1.68,1.20,1.42,1.88,1.67,1.24,1.39,1.67,1.60
1,1,1.45,1.73,1.62,1.31,1.48,1.74,1.71,1.30,1.49,...,1.68,1.20,1.42,1.88,1.67,1.24,1.39,1.67,1.60,1.26
2,2,1.73,1.62,1.31,1.48,1.74,1.71,1.30,1.49,1.94,...,1.20,1.42,1.88,1.67,1.24,1.39,1.67,1.60,1.26,1.41
3,3,1.62,1.31,1.48,1.74,1.71,1.30,1.49,1.94,1.68,...,1.42,1.88,1.67,1.24,1.39,1.67,1.60,1.26,1.41,1.68
4,4,1.31,1.48,1.74,1.71,1.30,1.49,1.94,1.68,1.26,...,1.88,1.67,1.24,1.39,1.67,1.60,1.26,1.41,1.68,1.59

In [16]:
def clear_outlier(df):

    idx = set()

    for i in range(len(df)):
        for j in range(len(df.iloc[0]) - 2):
            if ((df.iloc[i][j] * 0.9) <= df.iloc[i][j + 1] <= (df.iloc[i][j] * 1.1)) and ((df.iloc[i][j + 1] * 0.9) <= df.iloc[i][j + 2] <= (df.iloc[i][j + 1] * 1.1)):
                idx.add(i)

    return idx

In [17]:
idx = clear_outlier(water_df)

In [18]:
idx

{262144,
 262145,
 262146,
 262147,
 262148,
 262149,
 262150,
 262151,
 262152,
 262153,
 262154,
 262155,
 262156,
 262157,
 262158,
 318859,
 262190,
 262191,
 262192,
 262193,
 262194,
 262195,
 262196,
 262197,
 262198,
 262199,
 262200,
 262201,
 262202,
 262203,
 262204,
 262205,
 262206,
 262207,
 262208,
 262209,
 262210,
 262211,
 262212,
 262213,
 262214,
 262215,
 312632,
 312633,
 312634,
 312635,
 312636,
 262233,
 262234,
 262235,
 262236,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 262254,
 262255,
 262256,
 262257,
 262258,
 262259,
 262260,
 262261,
 262262,
 262263,
 262264,
 262265,
 262266,
 262267,
 312644,
 312645,
 312646,
 312647,
 312648,
 173,
 190,
 262356,
 262357,
 262358,
 262359,
 262360,
 262361,
 262362,
 262363,
 262364,
 262365,
 262366,
 262367,
 262368,
 262369,
 262370,
 262371,
 262372,
 262373,
 262374,
 262375,
 262376,
 262377,
 262378,
 262379,
 262380,
 262381,
 262382,
 262383,
 262384,
 262385,
 262386,
 262387,
 262388,
 262389,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 262431,
 262432,
 262433,
 262434,
 262435,
 262436,
 262437,
 262438,
 262439,
 262440,
 262441,
 262442,
 262443,
 262444,
 262445,
 262446,
 262447,
 262448,
 262449,
 262450,
 262451,
 262452,
 262453,
 262454,
 262455,
 262456,
 262470,
 262471,
 262472,
 262473,
 262474,
 262475,
 262476,
 262477,
 262478,
 262479,
 262480,
 262481,
 262482,
 262483,
 262484,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 262487,
 262488,
 262489,
 262490,
 262491,
 262492,
 262493,
 262494,
 262495,
 262531,
 262532,
 262533,
 262534,
 262535,
 262536,
 262537,
 262538,
 262539,
 262540,
 262541,
 262542,
 262543,
 262544,
 262545,
 262546,
 262547,
 262548,
 262549,
 262550,
 262551,
 262552,
 262553,
 262554,
 262555,
 262556,
 333464,
 262582,
 262583,
 262584,
 262585,
 262586,
 262587,
 262588,
 262589,
 262590,
 262591,
 262592,
 262593,
 262594,
 262595,
 262596,
 262597,
 262598,
 262599,
 262600,
 262601,
 262602,
 262603,
 262604,
 262605,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 262623,
 262624,
 262625,
 262626,
 262627,
 262628,
 262629,
 262630,
 262631,
 262632,
 262633,
 262634,
 262635,
 262636,
 262637,
 262638,
 262639,
 262640,
 262641,
 262642,
 262643,
 262713,
 262714,
 262715,
 262716,
 262717,
 262718,
 262719,
 262720,
 262721,
 262722,
 262723,
 262724,
 262725,
 262726,
 262727,
 262728,
 262729,
 262730,
 262731,
 262732,
 262733,
 262734,
 262735,
 262736,
 262737,
 262738,
 312631,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 262791,
 262792,
 262793,
 262794,
 262795,
 262796,
 262797,
 262798,
 262799,
 262800,
 262801,
 262803,
 262804,
 262805,
 262806,
 262807,
 262808,
 262809,
 262810,
 262811,
 262812,
 262813,
 262814,
 262815,
 262816,
 262817,
 682,
 683,
 684,
 685,
 686,
 687,
 262823,
 262824,
 262825,
 262826,
 262827,
 262828,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 262855,
 262856,
 262857,
 262858,
 262859,
 262860,
 262861,
 262862,
 262863,
 262864,
 262865,
 262866,
 262867,
 262868,
 262869,
 262870,
 262871,
 262872,
 262873,
 262874,
 262875,
 262876,
 262877,
 312637,
 262911,
 262912,
 262913,
 262914,
 262915,
 262916,
 262917,
 262927,
 262928,
 262929,
 262930,
 262931,
 262932,
 262933,
 262934,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 262952,
 262953,
 262954,
 262955,
 262956,
 262957,
 262958,
 262959,
 262960,
 262967,
 262968,
 262969,
 262970,
 262971,
 262972,
 262973,
 262974,
 262975,
 262976,
 262977,
 262978,
 262979,
 262980,
 262981,
 262982,
 262983,
 262984,
 262985,
 262986,
 262987,
 262988,
 262989,
 262990,
 262991,
 262992,
 262993,
 262994,
 262995,
 262996,
 262997,
 262998,
 262999,
 263000,
 263001,
 263002,
 263003,
 263004,
 263005,
 263006,
 263007,
 263008,
 312641,
 263034,
 263035,
 263036,
 263037,
 263038,
 263039,
 263040,
 263041,
 263042,
 263043,
 263044,
 263045,
 263046,
 263047,
 263048,
 263049,
 263050,
 263051,
 263052,
 263053,
 263054,
 263055,
 263056,
 263057,
 263058,
 263059,
 263060,
 263061,
 263062,
 263063,
 263064,
 263065,
 263066,
 263067,
 263068,
 263069,
 263070,
 263071,
 263072,
 263073,
 263074,
 263075,
 263076,
 263077,
 263078,
 263079,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 263249,
 263250,
 263251,
 263252,
 263253,
 263254,
 263255,
 263256,
 263257,
 263258,
 263284,
 263285,
 263286,
 263287,
 263288,
 263289,
 263290,
 263291,
 263292,
 263293,
 263294,
 263295,
 263296,
 263297,
 263298,
 263299,
 263300,
 263301,
 263302,
 263303,
 263304,
 263305,
 263306,
 263307,
 263308,
 263309,
 333494,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 333495,
 263367,
 263368,
 263369,
 263370,
 263371,
 263372,
 263373,
 263374,
 263375,
 263376,
 263377,
 263378,
 263379,
 263380,
 263381,
 263382,
 263383,
 263384,
 263385,
 263386,
 263387,
 263388,
 263389,
 263390,
 263391,
 263392,
 263393,
 263394,
 263395,
 263396,
 263397,
 263398,
 263399,
 263400,
 263401,
 263402,
 263403,
 263404,
 263405,
 263406,
 263407,
 263408,
 263409,
 263410,
 263411,
 263412,
 263413,
 263414,
 263415,
 263416,
 263417,
 263418,
 263419,
 263420,
 263421,
 263422,
 263423,
 263424,
 263425,
 263426,
 263427,
 263428,
 263429,
 263430,
 263431,
 263432,
 263433,
 263434,
 1348,
 1349,
 1350,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1367,
 1368,
 1369,
 1370,
 1371,
 1372,
 1373,
 1374,
 1375,
 1376,
 1377,
 1378,
 1379,
 1380,
 1381,
 1382,
 1383,
 1384,
 1385,
 1386,
 1387,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1399,
 1400,
 1401,
 1402,
 1403,
 1404,
 1405,
 1406,
 1407,
 1408,
 1409,
 263605,
 263606,
 263607,
 263608,
 263609,
 263610,
 263611,
 263612,
 263613,
 263614,
 263615,
 263616,
 263617,
 263618,
 263619,
 263620,
 263621,
 263622,
 263623,
 263624,
 263625,
 263626,
 263627,
 263628,
 263629,
 263630,
 263631,
 263632,
 263633,
 263634,
 263635,
 263636,
 263637,
 263638,
 263639,
 263640,
 263641,
 263642,
 263643,
 263644,
 263645,
 263646,
 263647,
 263648,
 263649,
 263650,
 263651,
 263652,
 263653,
 263654,
 263655,
 263656,
 263657,
 263658,
 263659,
 263660,
 263661,
 263662,
 263663,
 263664,
 1521,
 1522,
 1523,
 1524,
 1525,
 1526,
 1527,
 1528,
 1529,
 1530,
 1531,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1538,
 1539,
 1540,
 1541,
 1542,
 1543,
 1544,
 1545,
 1546,
 263688,
 263689,
 263690,
 263691,
 263692,
 263693,
 263694,
 263695,
 263696,
 263697,
 263698,
 263699,
 263700,
 263701,
 263702,
 263703,
 263704,
 263705,
 263706,
 263707,
 263708,
 263709,
 263710,
 263711,
 263712,
 263713,
 263720,
 263721,
 263722,
 263723,
 263724,
 263725,
 263726,
 263727,
 263728,
 263729,
 263730,
 263731,
 263732,
 263733,
 263734,
 263735,
 263736,
 263737,
 263738,
 263739,
 263740,
 263741,
 263742,
 ...}

In [19]:
# electric_df.drop(idx, axis = 0, inplace = True)
water_df.drop(idx, axis = 0, inplace = True)

In [20]:
water_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 239838 entries, 0 to 340997
Data columns (total 29 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  239838 non-null  int64
 1   0           239838 non-null  int64
 2   1           239838 non-null  int64
 3   2           239838 non-null  int64
 4   3           239838 non-null  int64
 5   4           239838 non-null  int64
 6   5           239838 non-null  int64
 7   6           239838 non-null  int64
 8   7           239838 non-null  int64
 9   8           239838 non-null  int64
 10  9           239838 non-null  int64
 11  10          239838 non-null  int64
 12  11          239838 non-null  int64
 13  12          239838 non-null  int64
 14  13          239838 non-null  int64
 15  14          239838 non-null  int64
 16  15          239838 non-null  int64
 17  16          239838 non-null  int64
 18  17          239838 non-null  int64
 19  18          239838 non-null  int64
 20  19          239838 non-null  int64
 21  20          239838 non-null  int64
 22  21          239838 non-null  int64
 23  22          239838 non-null  int64
 24  23          239838 non-null  int64
 25  24          239838 non-null  int64
 26  25          239838 non-null  int64
 27  26          239838 non-null  int64
 28  27          239838 non-null  int64
dtypes: int64(29)
memory usage: 54.9 MB

In [21]:
water_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 239838 entries, 0 to 340997
Data columns (total 29 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  239838 non-null  int64
 1   0           239838 non-null  int64
 2   1           239838 non-null  int64
 3   2           239838 non-null  int64
 4   3           239838 non-null  int64
 5   4           239838 non-null  int64
 6   5           239838 non-null  int64
 7   6           239838 non-null  int64
 8   7           239838 non-null  int64
 9   8           239838 non-null  int64
 10  9           239838 non-null  int64
 11  10          239838 non-null  int64
 12  11          239838 non-null  int64
 13  12          239838 non-null  int64
 14  13          239838 non-null  int64
 15  14          239838 non-null  int64
 16  15          239838 non-null  int64
 17  16          239838 non-null  int64
 18  17          239838 non-null  int64
 19  18          239838 non-null  int64
 20  19          239838 non-null  int64
 21  20          239838 non-null  int64
 22  21          239838 non-null  int64
 23  22          239838 non-null  int64
 24  23          239838 non-null  int64
 25  24          239838 non-null  int64
 26  25          239838 non-null  int64
 27  26          239838 non-null  int64
 28  27          239838 non-null  int64
dtypes: int64(29)
memory usage: 54.9 MB

In [22]:
# electric_df.to_csv('../Data/electric_df_clear_2.csv', index = 0)
water_df.to_csv('../Data/water_df_clear_2.csv', index = 0)