In [10]:
import pandas as pd

In [11]:
ELEC_DATA_PATH = '../Data/electric_df.csv'
WATER_DATA_PATH = '../Data/water_df.csv'

In [12]:
electric_df = pd.read_csv(ELEC_DATA_PATH, index_col = 0)
water_df = pd.read_csv(WATER_DATA_PATH, index_col = 0)

electric_df.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,1.23,1.45,1.73,1.62,1.31,1.48,1.74,1.71,1.30,1.49,...,1.68,1.20,1.42,1.88,1.67,1.24,1.39,1.67,1.60,1.26
1,1.45,1.73,1.62,1.31,1.48,1.74,1.71,1.30,1.49,1.94,...,1.20,1.42,1.88,1.67,1.24,1.39,1.67,1.60,1.26,1.41
2,1.73,1.62,1.31,1.48,1.74,1.71,1.30,1.49,1.94,1.68,...,1.42,1.88,1.67,1.24,1.39,1.67,1.60,1.26,1.41,1.68
3,1.62,1.31,1.48,1.74,1.71,1.30,1.49,1.94,1.68,1.26,...,1.88,1.67,1.24,1.39,1.67,1.60,1.26,1.41,1.68,1.59
4,1.31,1.48,1.74,1.71,1.30,1.49,1.94,1.68,1.26,1.39,...,1.67,1.24,1.39,1.67,1.60,1.26,1.41,1.68,1.59,1.24

In [13]:
idx = set()

for i in range(len(electric_df)):
    for j in range(len(electric_df.iloc[0]) - 2):
        if (electric_df.iloc[i][j] == electric_df.iloc[i][j + 1]) and (electric_df.iloc[i][j] == electric_df.iloc[i][j + 2]):
            idx.add(i)

In [14]:
idx

{38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 260542,
 260543,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 262336,
 262337,
 156348,
 262338,
 262339,
 262340,
 262341,
 156349,
 262342,
 262343,
 262344,
 262345,
 156350,
 262346,
 262347,
 262348,
 262349,
 156351,
 262350,
 262351,
 262352,
 262353,
 262354,
 156352,
 262355,
 262356,
 262357,
 262358,
 156353,
 262359,
 262360,
 262361,
 262362,
 156354,
 262363,
 156355,
 156356,
 156357,
 156358,
 156359,
 156360,
 156361,
 156362,
 156363,
 156364,
 156365,
 182418,
 182419,
 182420,
 182421,
 182422,
 340,
 262499,
 262500,
 262501,
 262502,
 262503,
 262504,
 262505,
 262506,
 262507,
 262508,
 262509,
 262510,
 262511,
 262512,
 262513,
 262514,
 262515,
 262516,
 262517,
 262518,
 262519,
 262520,
 262521,
 262522,
 262523,
 262524,
 262525,
 262530,
 262531,
 262532,
 262533,
 262534,
 262535,
 262536,
 262537,
 262538,
 262539,
 262540,
 262541,
 262542,
 262543,
 262544,
 262545,
 262546,
 262547,
 262548,
 262549,
 262550,
 262551,
 262552,
 262553,
 262554,
 262555,
 262556,
 262707,
 262708,
 262709,
 262710,
 262711,
 262712,
 262713,
 262714,
 262715,
 262716,
 262717,
 262718,
 262719,
 262720,
 262721,
 262722,
 262723,
 262724,
 262725,
 262726,
 262727,
 262728,
 262729,
 262730,
 262731,
 262732,
 262733,
 262831,
 262832,
 262833,
 262834,
 262835,
 262836,
 262837,
 262838,
 262839,
 262840,
 262841,
 262842,
 262843,
 262844,
 131773,
 131774,
 131775,
 131776,
 131777,
 131778,
 131779,
 131780,
 131781,
 131782,
 131783,
 131784,
 131785,
 131786,
 131787,
 131788,
 131789,
 131790,
 131791,
 131792,
 131793,
 131794,
 131795,
 131796,
 131797,
 131798,
 131799,
 131800,
 262910,
 262911,
 262912,
 262913,
 262914,
 262915,
 262916,
 262917,
 262918,
 262919,
 262920,
 131849,
 131850,
 131851,
 131852,
 131853,
 131854,
 131855,
 131856,
 131857,
 131858,
 131859,
 131860,
 131861,
 131862,
 131863,
 131864,
 131865,
 131866,
 131867,
 131868,
 131869,
 131870,
 131871,
 131872,
 131873,
 131874,
 131875,
 131876,
 208571,
 208572,
 208573,
 208574,
 262959,
 262960,
 208575,
 262961,
 262962,
 262963,
 262964,
 262965,
 208576,
 262966,
 262967,
 262968,
 262969,
 208577,
 262970,
 262971,
 262972,
 262973,
 208578,
 262974,
 262975,
 262976,
 262977,
 208579,
 262978,
 262979,
 262980,
 262981,
 208580,
 262982,
 262983,
 262984,
 262985,
 208581,
 208582,
 338846,
 338847,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 338851,
 338852,
 338853,
 131994,
 131995,
 131996,
 131997,
 131998,
 131999,
 132000,
 132001,
 132002,
 132003,
 132004,
 132005,
 132006,
 132007,
 132008,
 132009,
 132010,
 132011,
 132012,
 132013,
 132014,
 132015,
 132016,
 132017,
 132018,
 132019,
 132020,
 132021,
 132022,
 132023,
 132024,
 132025,
 132026,
 132027,
 132028,
 132029,
 132030,
 132031,
 132032,
 132033,
 132034,
 132035,
 132036,
 132037,
 132038,
 132039,
 132040,
 132041,
 132042,
 132043,
 132044,
 132045,
 263112,
 263113,
 263114,
 263115,
 263116,
 263117,
 263118,
 263119,
 263120,
 263121,
 263122,
 263123,
 263124,
 263125,
 263126,
 263127,
 263128,
 263129,
 263130,
 263131,
 263132,
 263133,
 263134,
 263135,
 263136,
 263137,
 263138,
 338868,
 338869,
 338870,
 338871,
 338872,
 338873,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 132148,
 132149,
 132150,
 132151,
 132152,
 132153,
 132154,
 132155,
 132156,
 132157,
 132158,
 132159,
 132160,
 132161,
 132162,
 132163,
 132164,
 132165,
 132166,
 132167,
 132168,
 132169,
 132170,
 132171,
 132172,
 132173,
 132174,
 132175,
 132176,
 312853,
 312854,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 132275,
 132276,
 132277,
 132278,
 132279,
 132280,
 132281,
 132282,
 132283,
 132284,
 132285,
 132286,
 132287,
 132288,
 132289,
 132290,
 132291,
 132292,
 132293,
 132294,
 312862,
 312863,
 312864,
 312865,
 312866,
 312867,
 312868,
 312869,
 312870,
 132350,
 132351,
 132352,
 132353,
 132354,
 132355,
 132356,
 132357,
 132358,
 132359,
 132360,
 132361,
 132362,
 132363,
 132364,
 132365,
 132366,
 132367,
 132368,
 132369,
 132370,
 132371,
 132372,
 132373,
 132374,
 132375,
 132376,
 263549,
 263550,
 263551,
 263552,
 263553,
 263554,
 263555,
 263556,
 263557,
 263558,
 263559,
 263560,
 263561,
 263562,
 263563,
 263564,
 263565,
 263566,
 263567,
 263568,
 263569,
 263570,
 263571,
 263572,
 263573,
 263574,
 263575,
 263605,
 263606,
 263607,
 263608,
 263609,
 263610,
 263611,
 263612,
 263613,
 263614,
 263615,
 263616,
 263617,
 263618,
 263619,
 263620,
 263621,
 263622,
 263623,
 263624,
 263625,
 263626,
 263627,
 263628,
 263629,
 263630,
 263631,
 263759,
 263760,
 263761,
 263762,
 263763,
 263764,
 263765,
 263766,
 263767,
 263768,
 263769,
 263770,
 263771,
 263772,
 263773,
 263774,
 263775,
 263776,
 263777,
 263778,
 263779,
 263780,
 263781,
 263782,
 263783,
 263784,
 263785,
 132719,
 132720,
 132721,
 132722,
 132723,
 132724,
 132725,
 132726,
 132727,
 132728,
 132729,
 132730,
 132731,
 132732,
 132733,
 132734,
 132735,
 132736,
 132737,
 132738,
 132739,
 132740,
 132741,
 132742,
 132743,
 132744,
 132745,
 339018,
 132822,
 132823,
 132824,
 132825,
 132826,
 132827,
 132828,
 132829,
 132830,
 132831,
 132832,
 132833,
 132834,
 132835,
 132836,
 132837,
 132838,
 132839,
 132840,
 132841,
 132842,
 132843,
 132844,
 132845,
 132846,
 132847,
 132848,
 339022,
 339023,
 339024,
 339025,
 339026,
 339027,
 328311,
 132933,
 132934,
 132935,
 1864,
 1865,
 1866,
 1867,
 1868,
 1869,
 1870,
 1871,
 1872,
 1873,
 1874,
 1875,
 1876,
 1877,
 1878,
 1879,
 1880,
 1881,
 1882,
 1883,
 1884,
 1885,
 1886,
 1887,
 1888,
 1889,
 1890,
 1891,
 132962,
 132963,
 132964,
 132965,
 132966,
 132967,
 132968,
 132969,
 132970,
 132971,
 132972,
 132973,
 132974,
 132975,
 132976,
 132977,
 132978,
 132979,
 132980,
 132981,
 132982,
 132983,
 132984,
 132985,
 132986,
 132987,
 132988,
 264059,
 264060,
 264061,
 264062,
 264063,
 264064,
 264065,
 264066,
 132999,
 133000,
 133001,
 133002,
 133003,
 133004,
 133005,
 133006,
 133007,
 133008,
 133009,
 133010,
 133011,
 133012,
 133013,
 133014,
 133015,
 133016,
 133017,
 133018,
 133019,
 133020,
 133021,
 133022,
 133023,
 133024,
 133025,
 133026,
 328316,
 328317,
 331379,
 328318,
 328319,
 286982,
 328320,
 286983,
 286984,
 286985,
 286986,
 2111,
 2112,
 2113,
 2114,
 2115,
 2116,
 2117,
 2118,
 2119,
 2120,
 2121,
 2122,
 2123,
 2124,
 2125,
 2126,
 2127,
 2128,
 2129,
 2130,
 2131,
 2132,
 2133,
 2134,
 2135,
 2136,
 2137,
 2138,
 264279,
 264280,
 264281,
 264282,
 264283,
 264284,
 264285,
 264286,
 264287,
 264288,
 264289,
 264290,
 264291,
 264292,
 264293,
 264294,
 264295,
 264296,
 264297,
 264298,
 264299,
 264300,
 264301,
 264302,
 264303,
 264304,
 264305,
 286996,
 286997,
 133241,
 133242,
 133243,
 133244,
 133245,
 133246,
 133247,
 133248,
 133249,
 133250,
 133251,
 133252,
 133253,
 133254,
 133255,
 133256,
 133257,
 133258,
 133259,
 133260,
 133261,
 133262,
 133263,
 133264,
 133265,
 133266,
 133267,
 287003,
 264461,
 264462,
 264463,
 264464,
 264465,
 264466,
 264467,
 264468,
 264469,
 264470,
 264471,
 264472,
 264473,
 264474,
 264475,
 264476,
 264477,
 264478,
 264479,
 264480,
 264481,
 264482,
 264483,
 264484,
 264485,
 264486,
 264487,
 331383,
 133636,
 133637,
 133638,
 133639,
 133640,
 133641,
 133642,
 133643,
 133644,
 133645,
 133646,
 133647,
 133648,
 133649,
 133650,
 133651,
 133652,
 133653,
 133654,
 133655,
 133656,
 133657,
 133658,
 133659,
 133660,
 133661,
 133662,
 2771,
 2772,
 2773,
 2774,
 2775,
 2776,
 2777,
 2778,
 2779,
 2780,
 2781,
 2782,
 2783,
 2784,
 2785,
 2786,
 2787,
 2788,
 2789,
 2790,
 ...}

In [15]:
electric_df.drop(idx, axis = 0, inplace = True)
water_df.drop(idx, axis = 0, inplace = True)

In [16]:
electric_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285998 entries, 0 to 339999
Data columns (total 29 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       285998 non-null  float64
 1   1       285998 non-null  float64
 2   2       285998 non-null  float64
 3   3       285998 non-null  float64
 4   4       285998 non-null  float64
 5   5       285998 non-null  float64
 6   6       285998 non-null  float64
 7   7       285998 non-null  float64
 8   8       285998 non-null  float64
 9   9       285998 non-null  float64
 10  10      285998 non-null  float64
 11  11      285998 non-null  float64
 12  12      285998 non-null  float64
 13  13      285998 non-null  float64
 14  14      285998 non-null  float64
 15  15      285998 non-null  float64
 16  16      285998 non-null  float64
 17  17      285998 non-null  float64
 18  18      285998 non-null  float64
 19  19      285998 non-null  float64
 20  20      285998 non-null  float64
 21  21      285998 non-null  float64
 22  22      285998 non-null  float64
 23  23      285998 non-null  float64
 24  24      285998 non-null  float64
 25  25      285998 non-null  float64
 26  26      285998 non-null  float64
 27  27      285998 non-null  float64
 28  28      285998 non-null  float64
dtypes: float64(29)
memory usage: 65.5 MB

In [17]:
water_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285998 entries, 0 to 339999
Data columns (total 29 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       285998 non-null  int64
 1   1       285998 non-null  int64
 2   2       285998 non-null  int64
 3   3       285998 non-null  int64
 4   4       285998 non-null  int64
 5   5       285998 non-null  int64
 6   6       285998 non-null  int64
 7   7       285998 non-null  int64
 8   8       285998 non-null  int64
 9   9       285998 non-null  int64
 10  10      285998 non-null  int64
 11  11      285998 non-null  int64
 12  12      285998 non-null  int64
 13  13      285998 non-null  int64
 14  14      285998 non-null  int64
 15  15      285998 non-null  int64
 16  16      285998 non-null  int64
 17  17      285998 non-null  int64
 18  18      285998 non-null  int64
 19  19      285998 non-null  int64
 20  20      285998 non-null  int64
 21  21      285998 non-null  int64
 22  22      285998 non-null  int64
 23  23      285998 non-null  int64
 24  24      285998 non-null  int64
 25  25      285998 non-null  int64
 26  26      285998 non-null  int64
 27  27      285998 non-null  int64
 28  28      285998 non-null  int64
dtypes: int64(29)
memory usage: 65.5 MB

In [18]:
electric_df.to_csv('../Data/electric_df_clear_29_days.csv', index = 0)
water_df.to_csv('../Data/water_df_clear_29_days.csv', index = 0)